### ISSUE TITLE
CrosEC.kext is worked on  Sonoma ,but Mojave doesn't.

### ISSUE THREAD

**Issue by hk860566999** [1Revenger1/CrosEC#1]
Darwin 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

/Library/Extensions/CrosEC.kext - no compatible dependency found for as.vit9696.VirtualSMC.
Code Signing Failure: not code signed
Dependency Resolution Failures:
    Only incompatible kexts found for these libraries:
        as.vit9696.Lilu
        as.vit9696.VirtualSMC

Diagnostics for /Library/Extensions/CrosEC.kext:
Dependency Resolution Failures:
    Only incompatible kexts found for these libraries:
        as.vit9696.Lilu
        as.vit9696.VirtualSMC

**Comment by averycblack** [comment]
How are you loading CrosEC.kext?
If your trying to load it via kextutil or kextload, you will need to add Lilu.kext and VirtualSMC.kext to your load command.
`kexxtutil -vvvv -d <path to Lilu.kext>/Lilu.kext -d <path to VirtualSMC.kext>/VirtualSMC.kext ./CrosEC.kext`

**Comment by hk860566999** [comment]
sudo kextutil -vvvv -d ./Lilu.kext -d VirtualSMC.kext  CrosEC.kext
Defaulting to kernel file '/System/Library/Kernels/kernel'
Kext with invalid signatured (-67062) allowed: <OSKext 0x7fbf0fe03360 [0x7fffa70cb8e0]> { URL = "file:///private/tmp/CrosEC.kext/", ID = "com.1Revenger1.CrosEC" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7fbf0fc00c20 [0x7fffa70cb8e0]> { URL = "file:///private/tmp/Lilu.kext/", ID = "as.vit9696.Lilu" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7fbf0fc00e90 [0x7fffa70cb8e0]> { URL = "file:///private/tmp/VirtualSMC.kext/", ID = "as.vit9696.VirtualSMC" }
Code Signing Failure: not code signed
/private/tmp/CrosEC.kext appears to be loadable (not including linkage for on-disk libraries).
Loading /private/tmp/CrosEC.kext.
Disabling KextAudit: SIP is off
KextAudit initialized: audit=F
(kernel) kxld[com.1Revenger1.CrosEC]: The super class vtable '__ZTV9IOService' for vtable '__ZTV14SMCLightSensor' is out of date. Make sure your kext has been built against the correct headers.
(kernel) kxld[com.1Revenger1.CrosEC]: The super class vtable '__ZTV9IOService' for vtable '__ZTV15CrosECDeviceNub' is out of date. Make sure your kext has been built against the correct headers.
(kernel) kxld[com.1Revenger1.CrosEC]: The super class vtable '__ZTV9IOService' for vtable '__ZTV15CrosECSensorHub' is out of date. Make sure your kext has been built against the correct headers.
(kernel) kxld[com.1Revenger1.CrosEC]: The super class vtable '__ZTV12IOUserClient' for vtable '__ZTV16CrosECUserClient' is out of date. Make sure your kext has been built against the correct headers.
(kernel) kxld[com.1Revenger1.CrosEC]: The super class vtable '__ZTV9IOService' for vtable '__ZTV23CrosECKeyboardBacklight' is out of date. Make sure your kext has been built against the correct headers.
(kernel) kxld[com.1Revenger1.CrosEC]: The super class vtable '__ZTV9IOService' for vtable '__ZTV9CrosECBus' is out of date. Make sure your kext has been built against the correct headers.
(kernel) Can't load kext com.1Revenger1.CrosEC - link failed.
(kernel) Failed to load executable for kext com.1Revenger1.CrosEC.
(kernel) Kext com.1Revenger1.CrosEC failed to load (0xdc008016).
(kernel) Failed to load kext com.1Revenger1.CrosEC (error 0xdc008016).
Failed to load /private/tmp/CrosEC.kext - (libkern/kext) link error.
Failed to load /private/tmp/CrosEC.kext - (libkern/kext) link error.
Check library declarations for your kext with kextlibs(8).

**Comment by averycblack** [comment]
[CrosEC-1.0.1-DEBUG.zip](https://github.com/Chromeintosh/CrosEC/files/13883860/CrosEC-1.0.1-DEBUG.zip)
Ah, I forgot that I had the min version set to Catalina. Here is a build set for 10.11/El Capitan and newer. Let me know if that works and I'll commit that.

**Comment by hk860566999** [comment]
Sorry, the error is still reported as follows. I'm not sure if it's a problem with Lilu or VirtualSMC versions. They are both the latest release versions.

sudo kextutil -vvvv -d ./Lilu.kext -d VirtualSMC.kext  CrosEC.kext
Defaulting to kernel file '/System/Library/Kernels/kernel'
Kext with invalid signatured (-67062) allowed: <OSKext 0x7f83ad411880 [0x7fffa0d4c8e0]> { URL = "file:///private/tmp/CrosEC.kext/", ID = "com.1Revenger1.CrosEC" }
Kext rejected due to improper filesystem permissions: <OSKext 0x7f83af804a70 [0x7fffa0d4c8e0]> { URL = "file:///private/tmp/Lilu.kext/", ID = "as.vit9696.Lilu" }
Rejecting invalid/inauthentic kext for bundle id as.vit9696.Lilu at location file:///private/tmp/Lilu.kext/.
/private/tmp/CrosEC.kext - no compatible dependency found for as.vit9696.Lilu.
Kext rejected due to improper filesystem permissions: <OSKext 0x7f83af805f90 [0x7fffa0d4c8e0]> { URL = "file:///private/tmp/VirtualSMC.kext/", ID = "as.vit9696.VirtualSMC" }
Rejecting invalid/inauthentic kext for bundle id as.vit9696.VirtualSMC at location file:///private/tmp/VirtualSMC.kext/.
/private/tmp/CrosEC.kext - no compatible dependency found for as.vit9696.VirtualSMC.
Rejecting invalid/inauthentic kext for bundle id as.vit9696.Lilu at location file:///private/tmp/Lilu.kext/.
/private/tmp/CrosEC.kext - no compatible dependency found for as.vit9696.Lilu.
Rejecting invalid/inauthentic kext for bundle id as.vit9696.VirtualSMC at location file:///private/tmp/VirtualSMC.kext/.
/private/tmp/CrosEC.kext - no compatible dependency found for as.vit9696.VirtualSMC.
Rejecting invalid/inauthentic kext for bundle id as.vit9696.Lilu at location file:///private/tmp/Lilu.kext/.
/private/tmp/CrosEC.kext - no compatible dependency found for as.vit9696.Lilu.
Rejecting invalid/inauthentic kext for bundle id as.vit9696.VirtualSMC at location file:///private/tmp/VirtualSMC.kext/.
/private/tmp/CrosEC.kext - no compatible dependency found for as.vit9696.VirtualSMC.
Code Signing Failure: not code signed
Dependency Resolution Failures:
    Only incompatible kexts found for these libraries:
        as.vit9696.Lilu
        as.vit9696.VirtualSMC
Sorry, the error is still reported as follows. I'm not sure if it's a problem with Lilu or VirtualSMC versions. They are both the latest release versions.
Diagnostics for /private/tmp/CrosEC.kext:
Dependency Resolution Failures:
    Only incompatible kexts found for these libraries:
        as.vit9696.Lilu
        as.vit9696.VirtualSMC

**Comment by averycblack** [comment]
You need to the owner for VirtualSMC and Lilu as root, like with CrosEC.

**Comment by hk860566999** [comment]
Yes they are all root:wheel group ,I ran the` chown -R root:wheel `command for all kexts.

**Comment by averycblack** [comment]
Not entirely sure then - that's usually what the errors below mean:
- `Kext rejected due to improper filesystem permissions: <OSKext 0x7f83af804a70 [0x7fffa0d4c8e0]> { URL = "file:///private/tmp/Lilu.kext/", ID = "as.vit9696.Lilu" }`
- `Rejecting invalid/inauthentic kext for bundle id as.vit9696.Lilu at location file:///private/tmp/Lilu.kext/.
/private/tmp/CrosEC.kext - no compatible dependency found for as.vit9696.Lilu.`
The errors don't seem related to CrosEC anymore.

**Comment by hk860566999** [comment]
The error message of [CrosEC-1.0.1-DEBUG.zip] is the same as before

sudo kextutil -vvvv -d  ./VirtualSMC.kext -d ./Lilu.kext  CrosEC.kext
Defaulting to kernel file '/System/Library/Kernels/kernel'
Kext with invalid signatured (-67062) allowed: <OSKext 0x7fc536c00a00 [0x7fffa0b6c8e0]> { URL = "file:///Library/Extensions/CrosEC.kext/", ID = "com.1Revenger1.CrosEC" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7fc536c04780 [0x7fffa0b6c8e0]> { URL = "file:///Library/Extensions/Lilu.kext/", ID = "as.vit9696.Lilu" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7fc536c05000 [0x7fffa0b6c8e0]> { URL = "file:///Library/Extensions/VirtualSMC.kext/", ID = "as.vit9696.VirtualSMC" }
Code Signing Failure: not code signed
/Library/Extensions/CrosEC.kext appears to be loadable (not including linkage for on-disk libraries).
Loading /Library/Extensions/CrosEC.kext.
Disabling KextAudit: SIP is off
KextAudit initialized: audit=F
(kernel) kxld[com.1Revenger1.CrosEC]: The super class vtable '__ZTV9IOService' for vtable '__ZTV14SMCLightSensor' is out of date. Make sure your kext has been built against the correct headers.
(kernel) kxld[com.1Revenger1.CrosEC]: The super class vtable '__ZTV9IOService' for vtable '__ZTV15CrosECDeviceNub' is out of date. Make sure your kext has been built against the correct headers.
(kernel) kxld[com.1Revenger1.CrosEC]: The super class vtable '__ZTV9IOService' for vtable '__ZTV15CrosECSensorHub' is out of date. Make sure your kext has been built against the correct headers.
(kernel) kxld[com.1Revenger1.CrosEC]: The super class vtable '__ZTV12IOUserClient' for vtable '__ZTV16CrosECUserClient' is out of date. Make sure your kext has been built against the correct headers.
(kernel) kxld[com.1Revenger1.CrosEC]: The super class vtable '__ZTV9IOService' for vtable '__ZTV23CrosECKeyboardBacklight' is out of date. Make sure your kext has been built against the correct headers.
(kernel) kxld[com.1Revenger1.CrosEC]: The super class vtable '__ZTV9IOService' for vtable '__ZTV9CrosECBus' is out of date. Make sure your kext has been built against the correct headers.
(kernel) Can't load kext com.1Revenger1.CrosEC - link failed.
(kernel) Failed to load executable for kext com.1Revenger1.CrosEC.
(kernel) Kext com.1Revenger1.CrosEC failed to load (0xdc008016).
(kernel) Failed to load kext com.1Revenger1.CrosEC (error 0xdc008016).
Failed to load /Library/Extensions/CrosEC.kext - (libkern/kext) link error.
Failed to load /Library/Extensions/CrosEC.kext - (libkern/kext) link error.
Check library declarations for your kext with kextlibs(8).

**Comment by averycblack** [comment]
https://github.com/Chromeintosh/CrosEC/actions/runs/7566871583
Want to give the artifacts listed here a shot? I wonder if something was messed up in my build environment. Had somebody test it on both High Sierra and Lion.

**Comment by hk860566999** [comment]
Great, it works. Mojave 10.14.6 (18G87)
kextstat |grep CrosEC
   42    0 0xffffff7f85275000 0x8000     0x8000     com.1Revenger1.CrosEC (1) 812435A2-9A4C-3153-8187-17047F2A8879 <38 37 12 6 5 3>

 uname -a
Darwin ENiGMA4 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

ectool hello
EC says hello!

**Comment by averycblack** [comment]
Released 1.0.1 with these changes, thanks for testing.
